language: crystal
env:
  - SFML=2.3.2
  - SFML=2.4.2
  - SFML=2.4.2 SAFE=ON
dist: trusty
addons:
  apt:
    packages: [
      build-essential, cmake, git, libx11-dev, freeglut3-dev, libxcb-image0-dev, libudev-dev,
      libjpeg8-dev, libopenal-dev, libsndfile1-dev, libfreetype6-dev, libxrandr-dev
    ]
before_install:
  - |
    curl -L "https://github.com/SFML/SFML/archive/$SFML.tar.gz" | tar -xz &&
    cd SFML* &&
    cmake . &&
    make &&
    export sfml="$(pwd)" &&
    export {LD_,}LIBRARY_PATH="$sfml/lib" &&
    cd ..
script:
  - |
    cmake . -DCRSFML_SAFE=$SAFE -DCMAKE_MODULE_PATH="$sfml/cmake/Modules" -DSFML_ROOT="$sfml" -DSFML_INCLUDE_DIR="$sfml/include" &&
    make &&
    export {LD_,}LIBRARY_PATH="$(pwd)/voidcsfml${LIBRARY_PATH:+:$LIBRARY_PATH}"
  - |
    crystal doc
  - |
    cd examples
    for f in *.cr; do
        crystal build "$f" || error=true
    done
    test -z $error
