language: crystal
env:
  - SFML=2.3.2
  - SFML=2.4.1
before_install:
  - sudo apt-get install -qy build-essential cmake git libx11-dev freeglut3-dev libxcb-image0-dev libudev-dev libjpeg8-dev libopenal-dev libsndfile1-dev libfreetype6-dev libxrandr-dev
  - |
    curl -L "https://github.com/SFML/SFML/archive/$SFML.tar.gz" | tar -xz
    cd SFML*
    cmake . && make
    sudo make install
    cd ..
script:
  - |
    cmake . && make &&
    export LIBRARY_PATH="$PWD/voidcsfml/lib"
  - crystal doc
  - |
    cd examples
    for f in *.cr; do
        crystal build "$f" || error=true
    done
    test -z $error
sudo: required
dist: trusty
