language: crystal
before_install:
  - sudo apt-get install -qy build-essential cmake git libx11-dev freeglut3-dev libxcb-image0-dev libudev-dev libjpeg8-dev libopenal-dev libsndfile1-dev libfreetype6-dev
  - |
    git clone https://github.com/SFML/SFML
    cd SFML
    git checkout "$(git describe --tags "$(git rev-list --tags --max-count=1)")"
    cmake . && make
    sudo make install
    cd ..
before_script:
  - mkdir build && cd build
script:
  - cmake -DCMAKE_MODULE_PATH="/usr/local/share/SFML/cmake/Modules" .. && make
  - crystal doc
sudo: required
dist: trusty
