language: crystal
matrix:
  include:
    - env: SFML=2.3.2
    - env: SFML=2.4.2
    - env: SFML=2.4.2 SAFE=ON
    - os: osx
    - os: osx
      env: SAFE=ON
  fast_finish: true
dist: trusty
addons:
  apt:
    packages: [
      build-essential, cmake, git, libx11-dev, freeglut3-dev, libxcb-image0-dev, libudev-dev,
      libjpeg8-dev, libopenal-dev, libsndfile1-dev, libfreetype6-dev, libxrandr-dev
    ]
before_install:
  - |
    if [ $TRAVIS_OS_NAME = osx ]; then
        brew install sfml &&
        sfml=(/usr/local/Cellar/sfml/2.*) && export sfml="$sfml"
    else
        curl -L "https://github.com/SFML/SFML/archive/$SFML.tar.gz" | tar -xz &&
        cd SFML* &&
        cmake . &&
        make &&
        export sfml="$(pwd)" &&
        export {LD_,}LIBRARY_PATH="$sfml/lib" &&
        cd ..
    fi
script:
  - |
    cmake . -DCRSFML_SAFE=$SAFE -DCMAKE_MODULE_PATH="$sfml/cmake/Modules" -DSFML_ROOT="$sfml" -DSFML_INCLUDE_DIR="$sfml/include" &&
    make &&
    export {LD_,}LIBRARY_PATH="$(pwd)/voidcsfml${LIBRARY_PATH:+:$LIBRARY_PATH}"
  - |
    crystal doc
  - |
    cd examples
    for example in *.cr; do
        echo "Building $example"
        crystal build "$example" || error=true
    done
    test -z $error
  - |
    if [ $TRAVIS_OS_NAME = osx ]; then
        for example in flippy_bird gl shader simple snakes text_input transformable; do
            echo "Running $example"
            ./$example & pid=$!
            sleep 3
            kill $pid || error=true
        done
    fi
    test -z $error
