language: crystal
os:
  - linux
  - osx
env:
  - SFML=2.5.1
jobs:
  fast_finish: true
  include:
    - env: SFML=2.4.2 CC=clang
    - env: SFML=2.3.2 CC=clang

addons:
  apt_packages:
    - cmake
    - libflac-dev
    - libfreetype6-dev
    - libgl1-mesa-dev
    - libopenal-dev
    - libudev-dev
    - libvorbis-dev
    - libx11-dev
    - libxrandr-dev
    # Only for SFML 2.4:
    - libjpeg-dev
    # Only for SFML 2.3:
    - freeglut3-dev
    - libxcb-image0-dev

install:
  - wget "https://github.com/SFML/SFML/archive/${SFML}.zip" -O sfml.zip
  - unzip sfml.zip
  - mv "SFML-${SFML}" sfml
  - pushd sfml
  - cmake .
  - cmake --build .
  - export SFML_INCLUDE_DIR="$(pwd)/include"
  - export {LD_,}LIBRARY_PATH="$(pwd)/lib"
  - popd

script:
  - touch generate.cr
  - make
  - |
    [[ ${SFML} < 2.5 ]] || git diff --exit-code

  - crystal doc

  - pushd examples
  - |
    for example in *.cr; do
        echo "Building ${example}"
        crystal build "${example}" || error=true
    done
    test -z ${error}
  - |
    if [ "${TRAVIS_OS_NAME}" != linux ]; then
        for example in flippy_bird gl shader simple text_input transformable; do
            echo "Running ${example}"
            "./${example}" & pid=$!
            sleep 3
            kill "${pid}" || error=true
        done
        test -z ${error}
    fi

cache:
  directories:
    - sfml-build
