site_name: CrSFML
use_directory_urls: false
edit_uri: blob/master/

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: green
    accent: teal

extra_css:
  - style.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.superfences
  - toc:
      permalink: "#"

plugins:
  - search
  - markdownextradata
  - gen-files:
      scripts:
        - tools/gen_doc_files.py
  - mkdocstrings:
      default_handler: crystal
      watch: [src]
  - literate-nav
  - section-index

extra:
  book:
    api: http://oprypin.github.io/crsfml/api/SF
    examples: https://github.com/oprypin/crsfml/tree/master/examples
    examples2: https://github.com/oprypin/crsfml-examples/tree/master
