site_name: CrSFML
use_directory_urls: false
edit_uri: blob/master/

theme:
  name: readthedocs
  highlightjs: false

extra_css:
  - codehilite.css
  - style.css

markdown_extensions:
  - codehilite:
      guess_lang: false

plugins:
  - search
  - markdownextradata
  - literate-nav:
      nav_file: README.md

extra:
  book:
    api: http://oprypin.github.io/crsfml/api/SF
    examples: https://github.com/oprypin/crsfml/tree/master/examples
    examples2: https://github.com/oprypin/crsfml-examples/tree/master
