site_name: CrSFML
use_directory_urls: false
edit_uri: blob/master/

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: green
    accent: teal

extra_css:
  - style.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - deduplicate-toc

plugins:
  - search
  - gen-files:
      scripts:
        - tools/gen_doc_files.py
  - mkdocstrings:
      default_handler: crystal
      watch: [src]
  - literate-nav
  - section-index
