site_name: CrSFML
site_url: https://oprypin.github.io/crsfml/
repo_url: https://github.com/oprypin/crsfml
edit_uri: blob/master/docs/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: green
    accent: green

extra_css:
  - style.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - deduplicate-toc

plugins:
  - search
  - gen-files:
      scripts:
        - tools/gen_doc_files.py
  - mkdocstrings:
      default_handler: crystal
      watch: [src]
  - literate-nav
  - section-index
