name: Deploy book
on:
  push:
    paths: ['tutorials/**', '.github/**']
  pull_request:
    paths: ['tutorials/**', '.github/**']
    branches: [master]
  schedule:
    - cron: '0 6 * * 6'
jobs:
  build:
    name: Deploy book
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r tutorials/requirements.txt
      - name: Build site
        run: tutorials/build.sh
      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: oprypin/push-to-gh-pages@v3
        with:
          publish_dir: tutorials/site
          destination_dir: tutorials
