name: Validate CI config
on:
  push:
    paths: ['.github/**']
  pull_request:
    paths: ['.github/**']
jobs:
  build:
    name: Validate CI config
    runs-on: ubuntu-latest
    steps:
      - name: Add Crystal repository
        run: |
          curl -sL "https://keybase.io/crystal/pgp_keys.asc" | sudo apt-key add -
          echo "deb https://dist.crystal-lang.org/apt crystal main" | sudo tee /etc/apt/sources.list.d/crystal.list
      - name: Install packages
        run: sudo apt-get -q update; sudo apt-get -qy install crystal libyaml-dev
      - name: Download sources
        uses: actions/checkout@v2
      - name: Generate config
        run: crystal run .github/workflows/generate.cr
      - name: Validate freshness
        run: git diff --exit-code
